# Generated by Django 6.0 on 2025-12-10 11:33

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarrierInfo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("carrier_name", models.CharField(max_length=255)),
                ("carrier_address", models.TextField(blank=True)),
                ("driver_name", models.CharField(default="Driver", max_length=255)),
                ("co_driver_name", models.CharField(default="NA", max_length=255)),
                ("truck_number", models.CharField(blank=True, max_length=64)),
                ("trailer_number", models.CharField(blank=True, max_length=64)),
                ("time_zone", models.CharField(default="UTC", max_length=64)),
                ("shipping_docs", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("current_location", models.CharField(max_length=255)),
                ("pickup_location", models.CharField(max_length=255)),
                ("dropoff_location", models.CharField(max_length=255)),
                (
                    "planned_start",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "cycle_used_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("use_34h_restart", models.BooleanField(default=False)),
                ("time_base", models.CharField(default="UTC", max_length=64)),
                (
                    "total_distance_miles",
                    models.DecimalField(decimal_places=2, default=0, max_digits=9),
                ),
                (
                    "total_drive_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "total_on_duty_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("status", models.CharField(default="planned", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "carrier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips",
                        to="trips.carrierinfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stop",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("start", "Start"),
                            ("pickup", "Pickup"),
                            ("dropoff", "Dropoff"),
                            ("fuel", "Fuel"),
                            ("break", "Break"),
                            ("rest", "Rest"),
                            ("other", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("sequence", models.PositiveIntegerField(default=0)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("planned_start", models.DateTimeField(blank=True, null=True)),
                ("duration_minutes", models.PositiveIntegerField(default=0)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="DutySegment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("off_duty", "Off Duty"),
                            ("sleeper", "Sleeper Berth"),
                            ("driving", "Driving"),
                            ("on_duty", "On Duty (Not Driving)"),
                        ],
                        max_length=24,
                    ),
                ),
                ("activity", models.CharField(blank=True, max_length=255)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("remarks", models.TextField(blank=True)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("day_index", models.PositiveIntegerField(default=1)),
                (
                    "distance_miles",
                    models.DecimalField(decimal_places=2, default=0, max_digits=9),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="segments",
                        to="trips.stop",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="Recap",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("day_index", models.PositiveIntegerField()),
                ("date", models.DateField()),
                (
                    "driving_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "on_duty_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "off_duty_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "sleeper_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "cycle_used_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "cycle_remaining_hours",
                    models.DecimalField(decimal_places=2, default=70, max_digits=6),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recaps",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["day_index"],
                "unique_together": {("trip", "day_index")},
            },
        ),
    ]
